// ADD
export const ADD_MACHINE = 'ADD_MACHINE';
export const ADD_MACHINE_SUCCESS = 'ADD_MACHINE_SUCCESS';
export const ADD_MACHINE_FAILURE = 'ADD_MACHINE_FAILURE';

// UPDATE
export const UPDATE_MACHINE = 'UPDATE_MACHINE';
export const UPDATE_MACHINE_SUCCESS = 'UPDATE_MACHINE_SUCCESS';
export const UPDATE_MACHINE_FAILURE = 'UPDATE_MACHINE_FAILURE';

// DELETE
export const DELETE_MACHINE = 'DELETE_MACHINE';
export const DELETE_MACHINE_SUCCESS = 'DELETE_MACHINE_SUCCESS';
export const DELETE_MACHINE_FAILURE = 'DELETE_MACHINE_FAILURE';

// GET ALL
export const GET_ALL_MACHINES = 'GET_ALL_MACHINES';
export const GET_ALL_MACHINES_SUCCESS = 'GET_ALL_MACHINES_SUCCESS';
export const GET_ALL_MACHINES_FAILURE = 'GET_ALL_MACHINES_FAILURE';
