// UPDATE
export const UPDATE_STAFFCONTRACT = 'UPDATE_STAFFCONTRACT';
export const UPDATE_STAFFCONTRACT_SUCCESS = 'UPDATE_STAFFCONTRACT_SUCCESS';
export const UPDATE_STAFFCONTRACT_FAILURE = 'UPDATE_STAFFCONTRACT_FAILURE';

